String = "$str"
Number = "$num"
Null = "$null"
Bool = "$bool"

Ref = "$ref"
RepeatableNode = "$rep_node"
RepeatableValues = "$rep_values"
RepeatableStartRowIndex = "$rep_start_row"
RepeatableEndRowIndex = "$rep_end_row"
